name = "notesprint"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "notes-db"
database_id = "e867079a-d387-4c77-9304-4210a3f60fd4"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "quiz-app-images"

